import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";

const banner = `/*
Color Tags — https://github.com/markosnarinian/obsidian-color-tags
Copyright (c) 2026 Markos Narinian — MIT

Derived from Color Marker by Central Brain Trust, also MIT:
https://github.com/ruisloan/obsidian-color-marker
Copyright (c) 2026 Central Brain Trust

This file is generated by esbuild from src/. Do not edit it directly.
*/
`;

const production = process.argv[2] === "production";

const context = await esbuild.context({
	banner: { js: banner },
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: ["obsidian", "electron", ...builtins],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: production ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: production,
});

if (production) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
